# Generated by Django 5.2.12 on 2026-03-24 09:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('settlement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('settlement_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_sent', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups_app.group')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settlements',
                'ordering': ['-settlement_date', '-created_at'],
                'indexes': [models.Index(fields=['group'], name='idx_settlement_group'), models.Index(fields=['from_user'], name='idx_settlement_from_user'), models.Index(fields=['to_user'], name='idx_settlement_to_user')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_settlement_amount_gt_zero'), models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='chk_settlement_users_distinct')],
            },
        ),
    ]
